language: ruby

rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby-19mode
  - rbx

gemfile:
  - gemfiles/rails_3_0.gemfile
  - gemfiles/rails_3_1.gemfile
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_edge.gemfile

matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx
    - rvm: ruby-head
  fast_finish: true
  exclude:
    - rvm: 1.9
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.0
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: rbx
      gemfile: gemfiles/rails_edge.gemfile

notifications:
  email: false
